Included points about the session.
praveenscience/TrailBlazer-ChitkaraUni pull request #4
Opened 2023-09-30 10:42 UTC by animeshchaudhri

* Added more points 

Fixes #1

2023-09-30 10:46 UTC, praveenscience requested changes
Fix the above said changes.

2023-09-30 10:46 UTC, praveenscience commented on ReadMe.md
> +* What is Open Source ?
Remove the space before `?`.

2023-09-30 10:46 UTC, praveenscience commented on ReadMe.md
> +* What is differnce between closed source and open source?
Make the right capitalisation and correct spelling.

```suggestion
* What is difference between Closed Source and Open Source?
```

2025-03-25 20:24 UTC, praveenscience approved these changes
LGTM! 💪🏻

2025-03-25 20:24 UTC, merged

2025-03-26 10:11 UTC, animeshchaudhri commented
@praveenscience  I have come a long way since then. Thank you!